import json
import unittest
import browser_features
from playwright.sync_api import expect


class ShelfDecor(unittest.TestCase):
    setUp = browser_features.Features.setUp
    tearDown = browser_features.Features.tearDown
    login = browser_features.Features.login
    save = browser_features.Features.save

    def change(self, selector, value):
        self.page.locator(selector).fill(str(value))
        self.page.locator(selector).dispatch_event('change')

    def test_decor_clipboard_recovery_and_limits(self):
        p = self.page
        self.login()
        p.goto(self.url+'/shelf_editor.html?id=R01')
        p.wait_for_function('isAdmin && recoveryReady')
        p.locator('#addDecor').click()
        self.change('#decor-text', 'Copied annotation')
        self.change('#decor-fillColor', '#abcdef')
        original = p.evaluate('({...currentDecor()})')
        p.locator('.shelf-decor.selected').focus()
        p.keyboard.press('Control+c')
        p.keyboard.press('Control+v')
        p.keyboard.press('Control+v')
        p.wait_for_function('shelf.data.decor.length===3')
        shapes = p.evaluate('shelf.data.decor')
        self.assertEqual(len({d['id'] for d in shapes}),3)
        for shape in shapes:
            for key in set(original)-{'id','x','y'}:
                self.assertEqual(shape[key], original[key])
        self.assertNotEqual(shapes[0]['x'],shapes[1]['x'])
        p.locator('#undo').click()
        self.assertEqual(p.evaluate('shelf.data.decor.length'),2)
        p.locator('#redo').click()
        self.assertEqual(p.evaluate('shelf.data.decor'),shapes)
        p.locator('#decor-text').focus()
        p.keyboard.press('Control+c')
        p.keyboard.press('Control+v')
        self.assertEqual(p.evaluate('shelf.data.decor.length'),3)
        p.evaluate('cacheDraft()')
        p.on('dialog',lambda d:d.accept())
        p.reload()
        p.wait_for_function('shelf.data?.decor?.length===3 && recoveryReady')
        self.assertEqual(p.evaluate('shelf.data.decor'),shapes)
        self.save('Decor clipboard')
        p.reload()
        p.wait_for_function('shelf.data?.decor?.length===3')
        self.assertEqual(p.evaluate('shelf.data.decor'),shapes)
        p.evaluate("()=>{chooseDecor(shelf.data.decor[0].id);shelf.copySelection();decorClipboard.w=shelf.data.cols;decorClipboard.h=shelf.data.rows;decorClipboard.x=0;decorClipboard.y=0;shelf.pasteSelection();}")
        self.assertEqual(p.evaluate('shelf.data.decor.length'),3)
        expect(p.locator('#status')).to_contain_text('No nearby position')
        p.evaluate("()=>{shelf.data.decor=Array.from({length:200},(_,i)=>({...shelf.data.decor[0],id:'D-'+i}));chooseDecor('D-0');shelf.copySelection();shelf.pasteSelection();}")
        self.assertEqual(p.evaluate('shelf.data.decor.length'),200)
        expect(p.locator('#status')).to_contain_text('200 decor')
        p.evaluate('shelf.clearClipboard()')
        self.assertIsNone(p.evaluate('decorClipboard'))

    def test_shelf_design_and_persistence(self):
        p = self.page
        self.login()
        p.goto(self.url+'/shelf_editor.html?id=R01')
        p.wait_for_function('isAdmin && shelf.data')
        for index, shape in enumerate(('rectangle', 'ellipse', 'triangle')):
            p.locator('#decorShape').select_option(shape)
            p.locator('#addDecor').click()
            self.change('#decor-text', 'Decor-only '+shape)
            self.change('#decor-x', index*7+1)
            self.change('#decor-y', 2)
            self.change('#decor-w', 5.25)
            self.change('#decor-h', 3.5)
            self.change('#decor-outlineWidth', 4)
            p.locator('#decor-outlineColor').fill('#ff0000')
            p.locator('#decor-outlineColor').dispatch_event('change')
            target = p.locator('.shelf-decor.selected')
            target.scroll_into_view_if_needed()
            box = target.bounding_box()
            before = p.evaluate('({...currentDecor()})')
            p.mouse.move(box['x']+box['width']/2, box['y']+box['height']/2)
            p.mouse.down()
            p.mouse.move(box['x']+box['width']/2+24, box['y']+box['height']/2+24, steps=5)
            p.mouse.up()
            after = p.evaluate('({...currentDecor()})')
            self.assertGreater(after['x'], before['x'])
            self.assertGreater(after['y'], before['y'])
        self.assertEqual(p.locator('.shelf-decor').count(), 3)
        self.assertEqual(p.evaluate('new Set(shelf.data.decor.map(d=>d.id)).size'), 3)
        self.change('#decor-w', 0)
        self.assertEqual(p.evaluate('currentDecor().w'), 5.25)
        # Resize interactively at a different cell size.
        p.locator('#zoomIn').click()
        handle = p.locator('.shelf-decor.selected .decor-resize')
        handle.scroll_into_view_if_needed()
        box = handle.bounding_box()
        p.mouse.move(box['x']+7, box['y']+7)
        p.mouse.down()
        p.mouse.move(box['x']+33, box['y']+33, steps=5)
        p.mouse.up()
        self.assertGreater(p.evaluate('currentDecor().w'), 5.25)
        p.locator('#decor-text').focus()
        p.keyboard.press('Control+a')
        p.keyboard.press('Backspace')
        p.locator('#decor-text').dispatch_event('change')
        self.assertEqual(p.evaluate('shelf.data.decor.length'), 3)
        self.assertEqual(p.evaluate('currentDecor().text'), '')
        expected = p.evaluate('shelf.data.decor')
        p.screenshot(path='/tmp/itr-decor-editor.png',full_page=True)
        p.evaluate('cacheDraft()')
        p.on('dialog', lambda dialog: dialog.accept())
        p.reload()
        p.wait_for_function('shelf.data?.decor?.length===3')
        self.assertEqual(p.evaluate('shelf.data.decor'), expected)
        p.locator('#shelfMode').select_option('complex')
        p.locator('#applyShelfMode').click()
        p.locator('#editDecor').uncheck()
        p.get_by_role('button', name='Empty cell, row 4, column 3', exact=True).click()
        p.locator('#addBin').click()
        self.change('#w', 1.5)
        self.change('#contents', 'Bin hover contents')
        p.locator('#editDecor').check()
        p.locator('.shelf-bin').click()
        self.assertEqual(p.evaluate('binAt().w'), 1.5)
        matrix = p.evaluate('shelf.data.matrix')
        p.locator('#decorSelection').select_option(expected[0]['id'])
        p.locator('#deleteDecor').click()
        self.assertEqual(p.evaluate('shelf.data.matrix'), matrix)
        p.locator('#undo').click()
        p.locator('#shelfMode').select_option('simple')
        p.locator('#applyShelfMode').click()
        self.assertEqual(p.locator('.shelf-bin').count(), 0)
        self.assertEqual(p.evaluate('shelf.data.decor'), expected)
        p.locator('#shelfMode').select_option('complex')
        p.locator('#applyShelfMode').click()
        self.save('Shelf design')
        p.locator('#back').click()
        p.wait_for_function('typeof lab!=="undefined" && lab.data')
        p.goto(self.url+'/shelf_editor.html?id=R01')
        p.wait_for_function('shelf.data?.decor?.length===3')
        p.locator('#auth').click()
        p.wait_for_function('!isAdmin')
        self.assertEqual(p.locator('#shelfReadOnly .shelf-decor').count(), 3)
        self.assertEqual(p.locator('#shelfReadOnly .decor-resize').count(), 0)
        p.locator('.readonly-bin').hover()
        expect(p.locator('.bin-tooltip')).to_contain_text('Bin hover contents')
        p.screenshot(path='/tmp/itr-decor-viewer.png',full_page=True)
        self.login()
        self.assertEqual(p.evaluate('shelf.data.decor'), expected)
        saved = json.loads((self.data/'shelves/R01.json').read_text())
        self.assertEqual(saved['decor'], expected)
        p.locator('#shelfMode').select_option('simple')
        p.locator('#applyShelfMode').click()
        self.save('Simple shelf design')
        p.locator('#auth').click()
        p.wait_for_function('!isAdmin')
        self.assertEqual(p.locator('#shelfReadOnly .shelf-decor').count(),3)
        self.assertEqual(p.locator('.readonly-bin').count(),0)
        self.assertEqual(json.loads((self.data/'shelves/R01.json').read_text())['matrix'],saved['matrix'])

    def test_copy_shelf_and_bins_keeps_decor(self):
        p=self.page
        self.login()
        p.goto(self.url+'/shelf_editor.html?id=R01')
        p.wait_for_function('isAdmin&&recoveryReady')
        p.locator('#shelfMode').select_option('complex')
        p.locator('#applyShelfMode').click()
        p.get_by_role('button',name='Empty cell, row 1, column 1',exact=True).click()
        p.locator('#addBin').click()
        p.locator('#addDecor').click()
        decor=p.evaluate('shelf.data.decor')
        p.locator('.shelf-bin').click()
        p.locator('.shelf-bin').focus()
        p.keyboard.press('Control+c')
        p.keyboard.press('Control+v')
        p.wait_for_function('shelfBins(shelf.data).length===2')
        self.assertEqual(p.evaluate('shelf.data.decor'),decor)
        p.locator('#back').click()
        p.wait_for_function('typeof lab!=="undefined"&&isAdmin&&recoveryReady')
        sid=p.evaluate("async()=>{choose('R01');await lab.copySelection();await lab.pasteSelection();return selected().id;}")
        self.assertNotEqual(sid,'R01')
        p.locator('#openShelf').click()
        p.wait_for_function('typeof shelf!=="undefined"&&isAdmin&&recoveryReady')
        self.assertEqual(p.evaluate('shelf.data.id'),sid)
        self.assertEqual(p.evaluate('shelf.data.decor'),decor)
        self.assertEqual(p.evaluate('shelfBins(shelf.data).length'),2)
        self.save('Copied designed shelf')
        self.assertEqual(json.loads((self.data/'shelves'/f'{sid}.json').read_text())['decor'],decor)


if __name__ == '__main__':
    unittest.main()
